name: A workflow for my Hello World file

on: push
jobs:

  build:

    name: Hello world action

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - uses: ./action-a

        with:

          MY_NAME: "Het Patel"
          NAME: Het
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
